init:
    image apple_idle = "ico/apple_idle.png"
    image apple_hover = "ico/apple_hover.png"
    image banana_idle = "ico/banana_idle.png"
    image banana_hover = "ico/banana_hover.png"
    image carrot_idle = "ico/carrot_idle.png"
    image carrot_hover = "ico/carrot_hover.png"
    image cherry_idle = "ico/cherry_idle.png"
    image cherry_hover = "ico/cherry_hover.png"
    image corn_idle = "ico/corn_idle.png"
    image corn_hover = "ico/corn_hover.png"
    image lemon_idle = "ico/lemon_idle.png"
    image lemon_hover = "ico/lemon_hover.png"
    image melon_idle = "ico/melon_idle.png"
    image melon_hover = "ico/melon_hover.png"
    image orange_idle = "ico/orange_idle.png"
    image orange_hover = "ico/orange_hover.png"
    image dum = "ico/dum.png"
